CREATE TABLE IF NOT EXISTS mri_qadmin_chat (
    message text NOT NULL,
    citizenid VARCHAR(50) NOT NULL,
    fullname VARCHAR(100) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
